export const SYNC_INTEGRATION_VALUES = {
  MAX_ITEMS_PER_QUERY: 100 as const,
  DATA_TASK_TYPE: 'Data' as const,
  FILING_TASK_TYPE: 'Filing' as const,
  TASK_READY_STATUS: 'Ready' as const,
  TASK_ACTIVE_STATUS: 'Active' as const,
  TASK_READY_FOR_TRANSFER: 'Ready for transfer' as const,
  CUSTOM_OBLIGATION_SOURCE: 'Custom' as const,
  TEMPLATE_OBLIGATION_SOURCE: 'Template' as const,
  STOP_PRODUCE_TASKS_STATUS: 'Stop' as const,
  CONTINUE_PRODUCE_TASKS_STATUS: 'Continue' as const,
  ADDED_BY_INTEGRATION: 'True' as const,
  IS_SYNCED_STATUS: 'True' as const,
  IS_CREATED: 'True' as const,
  CALENDAR_DAY: 'Calendar day' as const,
  WORK_DAY: 'Workday' as const,
  WEEKEND_BEGINS_FRIDAY: 'Friday' as const,
  WEEKEND_BEGINS_SATURDAY: 'Saturday' as const,
  WEEKEND_ROLL_BACKWARD: 'Roll Backward' as const,
  WEEKEND_ROLL_FORWARD: 'Roll Forward' as const,
};
