import { SYNC_INTEGRATION_COLUMNS } from '../../constants/sync-integration-columns';

export interface MondayItemCreationColumns {
  [SYNC_INTEGRATION_COLUMNS.TASK_TYPE_COLUMN]: string;
  [SYNC_INTEGRATION_COLUMNS.TASK_CLIENT_NAME_COLUMN]: string;
  [SYNC_INTEGRATION_COLUMNS.TASK_CLIENT_ID_COLUMN]: string;
  [SYNC_INTEGRATION_COLUMNS.TASK_BUSINESS_STREAM_NAME_COLUMN]: string;
  [SYNC_INTEGRATION_COLUMNS.TASK_BUSINESS_STREAM_ID_COLUMN]: string;
  [SYNC_INTEGRATION_COLUMNS.TASK_LEGAL_ENTITY_NAME_COLUMN]: string;
  [SYNC_INTEGRATION_COLUMNS.TASK_LEGAL_ENTITY_COUNTRY_COLUMN]: string;
  [SYNC_INTEGRATION_COLUMNS.TASK_OBLIGATION_DEFINITION_TYPE_TEXT_COLUMN]: string;
  [SYNC_INTEGRATION_COLUMNS.TASK_OBLIGATION_DEFINITION_TYPE_ID_COLUMN]: string;
  [SYNC_INTEGRATION_COLUMNS.TASK_TAX_REGISTRATION_COLUMN]: string;
  [SYNC_INTEGRATION_COLUMNS.TASK_COMPLEXITY_COLUMN]: string;
  [SYNC_INTEGRATION_COLUMNS.TASK_COMMENTS_COLUMN]: string;
  [SYNC_INTEGRATION_COLUMNS.TASK_SUBMISSION_DUE_DATE_COLUMN]: string;
  [SYNC_INTEGRATION_COLUMNS.TASK_DUE_DATE_COLUMN]: string;
  [SYNC_INTEGRATION_COLUMNS.TASK_TEXT_COLUMN]: string;
  [SYNC_INTEGRATION_COLUMNS.TASK_ROLE_COLUMN]: string;
  [SYNC_INTEGRATION_COLUMNS.TASK_BUDGETED_HOURS_COLUMN]: string;
  [SYNC_INTEGRATION_COLUMNS.TASK_OBLIGATION_ID_COLUMN]: string;
  [SYNC_INTEGRATION_COLUMNS.TASK_ID_COLUMN]: string;
  [SYNC_INTEGRATION_COLUMNS.TASK_RETURN_ID_COLUMN]: string;
  [SYNC_INTEGRATION_COLUMNS.TASK_ADDED_BY_STATUS]: string;
}
